### ISSUE TITLE
Coin case glitch emulation/Game Boy ROM color hacks

### ISSUE THREAD

**Issue by shawnline** [taisel/GameBoy-Online#13]
Just wondering, does this emulator properly emulate the Coin Case Glitch from Pokemon Gold and Silver?  Also, I attempted to play a colorized version of Pokemon Red, but it booted as a Game Boy rom in black and white, even though it displayed the Gen 2 window borders. Is this expected behavior? Thanks..

**Comment by taisel** [comment]
Question #1 no clue, didn't know about any coin case thing to start with.
 Question #2 This is a GB/GBC emulator, Pokemon Red's colorization is through Super GameBoy support, a system on cartridge for the Super NES, for which we do not emulate. It is not a GameBoy Color ROM.
