### ISSUE TITLE
why does this error happen?

### ISSUE THREAD

**Issue by fakeusername1029391323** [taisel/GameBoy-Online#2]
ROM image size too smal

**Comment by taisel** [comment]
The size should be a multiple of a ROM bank. Pad it with garbage data if you have to. It checks for that so it doesn't try to run random files that aren't binaries for the gb.

**Comment by fakeusername1029391323** [comment]
sorry i'm kinda of new at this kinda stuff. Where would I find the place to insert the code/garbage data?

**Comment by taisel** [comment]
Are you compiling your own binary? If you're re-using an existing binary, please make sure you unzip it first.

**Comment by fakeusername1029391323** [comment]
I have. I'm just kinda confused on how to add roms and get rid of that error msg. That's the only thing that's not working for me, everything else it loading quite fine ;)

**Comment by taisel** [comment]
just pad it with anything to get it to the minimum size then...

**Comment by fakeusername1029391323** [comment]
Where would I do this?

**Comment by taisel** [comment]
Depends on your IDE or environment. The compilation of your ROMs is out of the scope of this project, we only run the binary blobs.

**Comment by taisel** [comment]
Although it needs to be reviewed whether that minimum size should be enforced.

**Comment by fakeusername1029391323** [comment]
Got it
